/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan.titus.apps.view;

import javax.swing.JFrame;
import javax.swing.JPanel;
import perpustakaan.titus.apps.controller.MenuController;

/**
 *
 * @author Titus Utler
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    
    MenuController controller;
    AnggotaView anggotaView;
    BukuView bukuView;
    
    public MainView() {
        controller = new MenuController();
        anggotaView = new AnggotaView();
        bukuView = new BukuView();
        
        controller.setAnggotaView(anggotaView);
        controller.setBukuView(bukuView);
        initComponents();
        
        //deklarasikan kode untuk menset frame tidak bisa ubah ukuarannya
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        
    }
    
    public JPanel getHomePanel(){
        return homePanel;
    }
    public JPanel getMainPanel(){
        return mainPanel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnAnggota = new javax.swing.JButton();
        btnBuku = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM PERPUSTAKAAN PRODI IF");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masterPanel.setBackground(new java.awt.Color(26, 188, 156));
        masterPanel.setName("masterpanel"); // NOI18N
        masterPanel.setPreferredSize(new java.awt.Dimension(1200, 800));
        masterPanel.setRequestFocusEnabled(false);
        masterPanel.setVerifyInputWhenFocusTarget(false);
        masterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(26, 188, 156));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        menuPanel.setName("menuPanel"); // NOI18N
        menuPanel.setPreferredSize(new java.awt.Dimension(250, 720));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/titus/apps/asset/perpus.png"))); // NOI18N
        menuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 37, -1, 86));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUDAYAKAN");
        menuPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 141, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MEMBACA");
        menuPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 169, -1, -1));

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/titus/apps/asset/home.png"))); // NOI18N
        btnHome.setText("HOME");
        btnHome.setMargin(new java.awt.Insets(4, 14, 4, 14));
        btnHome.setPreferredSize(new java.awt.Dimension(200, 60));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        menuPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 349, 226, 46));

        btnAnggota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/titus/apps/asset/member.png"))); // NOI18N
        btnAnggota.setText("ANGGOTA");
        btnAnggota.setPreferredSize(new java.awt.Dimension(200, 60));
        btnAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnggotaMouseClicked(evt);
            }
        });
        menuPanel.add(btnAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 406, 226, 46));

        btnBuku.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/titus/apps/asset/book.png"))); // NOI18N
        btnBuku.setText("BUKU");
        btnBuku.setPreferredSize(new java.awt.Dimension(200, 60));
        btnBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBukuMouseClicked(evt);
            }
        });
        menuPanel.add(btnBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 463, 226, 46));

        btnAbout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/titus/apps/asset/about.png"))); // NOI18N
        btnAbout.setText("ABOUT US");
        btnAbout.setPreferredSize(new java.awt.Dimension(200, 60));
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });
        menuPanel.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 520, 226, 46));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpustakaan/titus/apps/asset/logout.png"))); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setToolTipText("");
        btnLogout.setPreferredSize(new java.awt.Dimension(200, 60));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        menuPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 577, 226, 46));

        masterPanel.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        mainPanel.setBackground(new java.awt.Color(26, 188, 156));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(890, 720));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(236, 240, 241));
        homePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        homePanel.setName("homePanel"); // NOI18N
        homePanel.setPreferredSize(new java.awt.Dimension(920, 720));
        homePanel.setRequestFocusEnabled(false);
        homePanel.setVerifyInputWhenFocusTarget(false);
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("HALAMAN UTAMA");
        homePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        mainPanel.add(homePanel, "card2");

        masterPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 11, 924, -1));

        getContentPane().add(masterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        controller.halamanUtama(this);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnggotaMouseClicked
        // TODO add your handling code here:
        controller.kelolaAnggota(this);
    }//GEN-LAST:event_btnAnggotaMouseClicked

    private void btnBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBukuMouseClicked
        // TODO add your handling code here:
        controller.kelolaBuku(this);
    }//GEN-LAST:event_btnBukuMouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        controller.about();
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        controller.logOut(this);
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAnggota;
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel masterPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables

}
